# Publish extension to Chrome Web Store
name: Publish extension
on:
  push:
    branches:
      - prod

jobs:
  package:
    name: Package extension for upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Zip the relevant files
        run: |
          cd extension
          zip -r release.zip *

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: release.zip
          path: extension/release.zip

  upload:
    name: Upload extension to Chrome Web Store
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: release.zip

      - name: Upload to Chrome Web Store
        uses: mobilefirstllc/cws-publish@latest
        with:
          action: 'publish'
          client_id: ${{ secrets.CLIENT_ID }}
          client_secret: ${{ secrets.CLIENT_SECRET }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
          extension_id: ${{ secrets.EXTENSION_ID }}
          zip_file: release.zip
